name: mitre-securing-ai
channels:
  - defaults
dependencies:
  - click>=7.1.*,<8.0 # mlflow/prefect requirement
  - cloudpickle>=1.3.0 # prefect requirement
  - cython
  - docker-py>=4.0.0 # mlflow requirement
  - entrypoints # mlflow requirement
  - gitpython>=2.1.0 # mlflow requirement
  - gunicorn # mlflow requirement
  - jinja2>=2.10.1,<3.0
  - nomkl
  - numpy>=1.18.0 # adversarial-robustness-toolbox requirement
  - pandas>=1.1.0 # mlflow/prefect requirement
  - pip
  - protobuf>=3.7.0 # mlflow requirement
  - psycopg2
  - python-dateutil>=2.8.0 # prefect requirement
  - python=3.9.*
  - pytz>=2018.7 # mlflow requirement
  - pyyaml>=5.1 # mlflow requirement
  - requests>=2.25 # prefect requirement
  - scipy>=1.4.1 # adversarial-robustness-toolbox requirement
  - simplejson
  - six # adversarial-robustness-toolbox requirement
  - sqlalchemy # mlflow requirement
  - sqlparse>=0.3.1 # mlflow requirement
  - werkzeug>=1.0.0,<2
  - pip:
      - alembic<2
      - boto3>=1.16.0 # mlflow requirement
      - databricks-cli>=0.8.7 # mlflow requirement
      - Flask
      - gorilla
      - mlflow==1.*
      - prometheus-flask-exporter # mlflow requirement
      - querystring-parser # mlflow requirement
