# This Software (Dioptra) is being made available as a public service by the
# National Institute of Standards and Technology (NIST), an Agency of the United
# States Department of Commerce. This software was developed in part by employees of
# NIST and in part by NIST contractors. Copyright in portions of this software that
# were developed by NIST contractors has been licensed or assigned to NIST. Pursuant
# to Title 17 United States Code Section 105, works of NIST employees are not
# subject to copyright protection in the United States. However, NIST may hold
# international copyright in software created by its employees and domestic
# copyright (or licensing rights) in portions of software that were assigned or
# licensed to NIST. To the extent that NIST holds copyright in this software, it is
# being made available under the Creative Commons Attribution 4.0 International
# license (CC BY 4.0). The disclaimers of the CC BY 4.0 license apply to all parts
# of the software developed or licensed by NIST.
#
# ACCESS THE FULL CC BY 4.0 LICENSE HERE:
# https://creativecommons.org/licenses/by/4.0/legalcode
version: "3.7"
networks:
  jtsexton:
services:
  minio:
    image: minio/minio:RELEASE.2020-07-12T19-14-17Z
    init: true
    restart: always
    hostname: minio-jtsexton
    container_name: minio-jtsexton
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    ports:
      - target: 9000
        published: 39023
        protocol: tcp
        mode: host
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    volumes:
      - type: bind
        source: ./s3
        target: /data
    networks:
      - jtsexton
  mlflow-tracking:
    image: dioptra/mlflow-tracking:0.0.0-1
    init: true
    restart: always
    hostname: mlflow-tracking
    container_name: mlflow-tracking-jtsexton
    depends_on:
      - minio
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 20s
      retries: 3
    ports:
      - target: 5000
        published: 35023
        protocol: tcp
        mode: host
    command:
      - --host
      - "0.0.0.0"
      - --default-artifact-root
      - "s3://mlflow-tracking/artifacts"
    environment:
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: minio123
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
    volumes:
      - type: bind
        source: ./mlruns
        target: /work/mlruns
    networks:
      - jtsexton
  tfcpu:
    image: dioptra/tensorflow2-cpu-py37:0.0.0-1
    init: true
    restart: "no"
    hostname: tfcpu
    container_name: tfcpu-jtsexton
    depends_on:
      - minio
      - mlflow-tracking
    environment:
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: minio123
      MLFLOW_EXPERIMENT_NAME: patch-defended-pt
      MLFLOW_TRACKING_URI: http://mlflow-tracking:5000
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      KMP_AFFINITY: "none"
      KMP_BLOCKTIME: "1"
      OMP_NUM_THREADS: "6"
      KMP_SETTINGS: "FALSE"
      USE_DAAL4PY_SKLEARN: "YES"
    volumes:
      - type: bind
        source: ./data
        target: /nfs/data
    networks:
      - jtsexton
  tfgpu:
    image: dioptra/tensorflow2-gpu-py37:0.0.0-1
    init: true
    restart: "no"
    hostname: tfgpu
    container_name: tfgpu-jtsexton
    depends_on:
      - minio
      - mlflow-tracking
    environment:
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: minio123
      MLFLOW_EXPERIMENT_NAME: patch-defended-pt
      MLFLOW_TRACKING_URI: http://mlflow-tracking:5000
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
    volumes:
      - type: bind
        source: ./data
        target: /nfs/data
      - type: bind
        source: /home/hhuang/For_Julian
        target: /nfs2/data

    networks:
      - jtsexton
