# This Software (Dioptra) is being made available as a public service by the
# National Institute of Standards and Technology (NIST), an Agency of the United
# States Department of Commerce. This software was developed in part by employees of
# NIST and in part by NIST contractors. Copyright in portions of this software that
# were developed by NIST contractors has been licensed or assigned to NIST. Pursuant
# to Title 17 United States Code Section 105, works of NIST employees are not
# subject to copyright protection in the United States. However, NIST may hold
# international copyright in software created by its employees and domestic
# copyright (or licensing rights) in portions of software that were assigned or
# licensed to NIST. To the extent that NIST holds copyright in this software, it is
# being made available under the Creative Commons Attribution 4.0 International
# license (CC BY 4.0). The disclaimers of the CC BY 4.0 license apply to all parts
# of the software developed or licensed by NIST.
#
# ACCESS THE FULL CC BY 4.0 LICENSE HERE:
# https://creativecommons.org/licenses/by/4.0/legalcode
name: patch-defended-pixel-threshold
channels:
  - defaults
  - conda-forge
dependencies:
  - autopep8
  - black
  - bottleneck
  - click
  - cloudpickle
  - cython
  - flake8
  - flake8-bugbear
  - h5py
  - ipython
  - isort
  - jinja2
  - joblib
  - jupyter
  - markupsafe
  - matplotlib
  - mypy
  - numexpr
  - numpy
  - pandas
  - pillow
  - pip=20.0.2
  - protobuf
  - pycodestyle
  - pydocstyle
  - pytables
  - python=3.8.*
  - pytz
  - pyyaml=5.3.0
  - requests
  - scikit-learn=0.22.1
  - scipy
  - setuptools=46.1.3
  - setuptools-scm=3.5.0
  - wheel=0.34.2
  - pip:
      - adversarial-robustness-toolbox
      - boto3
      - databricks-cli
      - docformatter
      - Flask
      - gorilla
      - markdown
      - mlflow
      - mnist
      - prometheus-flask-exporter
      - pyarrow
      - python-json-logger
      - rich
      - structlog
      - tabulate
      - tensorflow==2.1.0
      - typing-extensions
