name: dioptra
channels:
  - defaults
dependencies:
  - click>=7.1.*,<8.0 # mlflow/prefect requirement
  - cloudpickle>=1.3.0 # prefect requirement
  - cython
  - docker-py>=4.0.0 # mlflow requirement
  - entrypoints # mlflow requirement
  - gitpython>=2.1.0 # mlflow requirement
  - gunicorn # mlflow requirement
  - jinja2>=2.10.1,<3.0
  - nomkl
  - numpy>=1.18.0 # adversarial-robustness-toolbox requirement
  - pandas>=1.1.1 # mlflow/prefect requirement
  - pillow
  - pip
  - protobuf>=3.7.0 # mlflow requirement
  - psycopg2
  - python-dateutil>=2.8.0 # prefect requirement
  - python=3.9.*
  - pytz>=2018.7 # mlflow requirement
  - pyyaml>=5.1 # mlflow requirement
  - redis-py>=3.5.0 # prefect requirement
  - requests>=2.25 # prefect requirement
  - scipy>=1.4.1 # adversarial-robustness-toolbox requirement
  - simplejson
  - six # adversarial-robustness-toolbox requirement
  - sqlalchemy # mlflow requirement
  - sqlparse>=0.3.1 # mlflow requirement
  - werkzeug>=1.0.0,<2
  - pip:
      - alembic<2
      - boto3>=1.16.0 # mlflow requirement
      - databricks-cli>=0.8.7 # mlflow requirement
      - flask-accepts>=0.17.0,<1
      - Flask-Injector>=0.12.0,<1
      - Flask-Migrate>=2.5.0,<3
      - flask-restx>=0.2.0,<1
      - Flask-SQLAlchemy>=2.4.0,<3
      - Flask-WTF>=0.14.3,<1
      - Flask>=1.1.0,<2
      - gorilla
      - marshmallow>=3.9.0,<4
      - mlflow==1.*
      - multimethod>=1.5
      - passlib
      - prometheus-flask-exporter # mlflow requirement
      - pyarrow>=2.0.0
      - python-json-logger>=2.0.0
      - querystring-parser # mlflow requirement
      - rq>=1.5.0
      - structlog>=20.2.0
      - typing-extensions>=3.7.4.0
