# This Software (Dioptra) is being made available as a public service by the
# National Institute of Standards and Technology (NIST), an Agency of the United
# States Department of Commerce. This software was developed in part by employees of
# NIST and in part by NIST contractors. Copyright in portions of this software that
# were developed by NIST contractors has been licensed or assigned to NIST. Pursuant
# to Title 17 United States Code Section 105, works of NIST employees are not
# subject to copyright protection in the United States. However, NIST may hold
# international copyright in software created by its employees and domestic
# copyright (or licensing rights) in portions of software that were assigned or
# licensed to NIST. To the extent that NIST holds copyright in this software, it is
# being made available under the Creative Commons Attribution 4.0 International
# license (CC BY 4.0). The disclaimers of the CC BY 4.0 license apply to all parts
# of the software developed or licensed by NIST.
#
# ACCESS THE FULL CC BY 4.0 LICENSE HERE:
# https://creativecommons.org/licenses/by/4.0/legalcode
name: dioptra
channels:
  - defaults
dependencies:
  - click=7.1.*
  - cloudpickle=1.6.*
  - cython=0.29.*
  - docker-py=4.3.*
  - entrypoints=0.3
  - gitpython=3.1.*
  - gunicorn=20.0.*
  - jinja2=2.11.*
  - nomkl=3.0
  - numpy=1.19.*
  - pandas=1.1.*
  - pip
  - protobuf=3.13.0.1
  - psycopg2=2.8.*
  - python-dateutil=2.8.*
  - python=3.7.*
  - pytz=2020.1
  - pyyaml=5.3.1
  - requests=2.25.0
  - scipy=1.5.*
  - simplejson=3.17.*
  - six=1.13.0
  - sqlalchemy=1.3.13
  - sqlparse=0.4.*
  - werkzeug=1.0.*
  - pip:
      - alembic<=1.4.1
      - boto3>=1.16.0
      - databricks-cli==0.13.0
      - Flask>=1.1.0,<2
      - gorilla==0.3.0
      - mlflow==1.12.1
      - prometheus-flask-exporter==0.18.1
      - querystring-parser>=1.2.0
